#!/usr/bin/env bash
# 10-fizzbuzz displays numbers 1 to 100. If the number is divisible by 3, Fizz is printed. If the number is divisible by 5, Buzz is printed. If the number is divisible by 3 and 5, FizzBuzz is printed
for ((i=1; i<=100; i++)) do
    if [ $((i%3)) = 0 ] && [ $((i%5)) = 0 ]; then
        echo "FizzBuzz"
    elif [ $((i%3)) = 0 ]; then
        echo "Fizz"
    elif [ $((i%5)) = 0 ]; then
        echo "Buzz"
    else
        echo "$i"
    fi
done
