#!/usr/bin/env bash
# 11-reand_and_cut displays the content of the file /etc/passwd with some formatting
while i= read -r line 
do
    echo "$line" | cut --delimiter=: --fields=1,3,6
done < "/etc/passwd"
