#!/usr/bin/env bash
# 12-tell_the_story_of_passwd tells a story based on the /etc/passwd file
while IFS=: read -r field1 field2 field3 field4 field5 field6 field7
do
    echo "The user $field1 is part of the $field3 gang, lives in $field6 and rides $field7. $field4's place is protected by the passcode $field2, more info about the user here: $field5"
done < "/etc/passwd"
