#!/usr/bin/env bash
# 14-dig_the-data parses the IP and the HTTP status code out of an apache log file and sorts based on number of occurences
awk '{print $1, $9}' apache-access.log | sort | uniq -c | sort -nr
