#!/usr/bin/env bash
# This script is displaying "Best School" 10 times but says "Hi" on the 9th iteration
count=0;
while [ $count -lt 9 ]
do
    if [ $count -eq 8 ]
    then
        echo "Hi"
    fi
    echo "Best School"
    ((count++))
done
