#!/usr/bin/env bash
# 7-clock prints every minute and hour up to 12 hours and 59 minutes
hour=0
while [ $hour -le 24 ] 
do
    echo "Hour: $hour"
    minute=1
    
    while [ $minute -le 60 ]
    do
        echo $minute
        ((minute++))
    done

    ((hour++))
done