#!/usr/bin/env bash
# 9-to_file_or_not_to_file gives information about a file named "school"
file="school"
if [ -e $file ]; then
    echo "school file exists"

    if [ -s $file ]; then
        echo "school file is not empty"
    else
        echo "school file is empty"
    fi

    if [ -f $file ]; then
        echo "school file is a regular file"
    fi
else
    echo "school file does not exist"
fi