#!/usr/bin/env bash
# 11-manage_my_process manages 'manage_my_process'
case $1 in
    "start")
        sudo ./manage_my_process &
        echo "$$" > /var/run/my_process.pid
        echo "manage_my_process started"
        ;;
    "stop")
        sudo pkill -f "manage_my_process"
        rm /var/run/my_process.pid
        echo "manage_my_process stopped"
        ;;
    "restart")
        sudo pkill -f "manage_my_process"
        rm /var/run/my_process.pid
        sudo ./manage_my_process &
        echo "$$" > /var/run/my_process.pid
        echo "manage_my_process restarted"
        ;;
    *)
        echo "Usage: manage_my_process {start|stop|restart}"
        ;;
esac
