#!/usr/bin/env bash
# 11-manage_my_process manages 'manage_my_process'
option="$1"
case "$option" in
    "start")
        ./manage_my_process &
        sudo sh -c 'echo "$$" > sudo /var/run/my_process.pid'
        echo "manage_my_process started"
        ;;
    "stop")
        pkill -f "manage_my_process"
        rm /var/run/my_process.pid
        echo "manage_my_process stopped"
        ;;
    "restart")
        pkill -f "manage_my_process"
        rm /var/run/my_process.pid
        ./manage_my_process &
        sudo sh -c 'echo "$$" > sudo /var/run/my_process.pid'
        echo "manage_my_process restarted"
        ;;
    *)
        echo "Usage: manage_my_process {start|stop|restart}"
        ;;
esac
