#!/usr/bin/env bash
# 11-manage_my_process manages 'manage_my_process'
option="$1"
case "$option" in
    "start")
        ./manage_my_process &
        sudo sh -c 'echo "$$" > /var/run/my_process.pid'
        echo "manage_my_process started"
        ;;
    "stop")
        rm /var/run/my_process.pid
        echo "manage_my_process stopped"
        kill "$( pgrep -f /manage_my_process )"
        ;;
    "restart")
        rm /var/run/my_process.pid
        kill "$( pgrep -f /manage_my_process )"
        ./manage_my_process &
        sudo sh -c 'echo "$$" > /var/run/my_process.pid'
        echo "manage_my_process restarted"
        ;;
    *)
        echo "Usage: manage_my_process {start|stop|restart}"
        ;;
esac
